/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empMgmtApp.gui;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class OptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmpOptionsFrame
     */
    public OptionsFrame() {
        initComponents();       
        Toolkit t=Toolkit.getDefaultToolkit();
        Image obj=t.getImage("F:\\NetBeansProjects\\taj.jpg");
        super.setIconImage(obj);
        super.setTitle("EMPLOYEE MANAGEMENT APP.™");
        super.setLocationRelativeTo(null);
       

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrbAddEmp = new javax.swing.JRadioButton();
        jrbSearchEmp = new javax.swing.JRadioButton();
        jrbShowAllEmp = new javax.swing.JRadioButton();
        jrbQuit = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jrbUpdateEmp = new javax.swing.JRadioButton();
        jrbDeleteEmp = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jrbAddEmp.setBackground(new java.awt.Color(0, 0, 0));
        jrbAddEmp.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jrbAddEmp.setForeground(new java.awt.Color(255, 0, 0));
        jrbAddEmp.setText("add  employee");
        jrbAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAddEmpActionPerformed(evt);
            }
        });

        jrbSearchEmp.setBackground(new java.awt.Color(0, 0, 0));
        jrbSearchEmp.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jrbSearchEmp.setForeground(new java.awt.Color(255, 0, 0));
        jrbSearchEmp.setText("search  employee");
        jrbSearchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSearchEmpActionPerformed(evt);
            }
        });

        jrbShowAllEmp.setBackground(new java.awt.Color(0, 0, 0));
        jrbShowAllEmp.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jrbShowAllEmp.setForeground(new java.awt.Color(255, 0, 0));
        jrbShowAllEmp.setText("show  all  employee");

        jrbQuit.setBackground(new java.awt.Color(0, 0, 0));
        jrbQuit.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jrbQuit.setForeground(new java.awt.Color(255, 0, 0));
        jrbQuit.setText("quit");
        jrbQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbQuitActionPerformed(evt);
            }
        });

        btnDoTask.setBackground(new java.awt.Color(0, 0, 0));
        btnDoTask.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 0, 0));
        btnDoTask.setText("do  task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("select  your  choice");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));

        jrbUpdateEmp.setBackground(new java.awt.Color(0, 0, 0));
        jrbUpdateEmp.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jrbUpdateEmp.setForeground(new java.awt.Color(255, 0, 0));
        jrbUpdateEmp.setText("update  employee");
        jrbUpdateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbUpdateEmpActionPerformed(evt);
            }
        });

        jrbDeleteEmp.setBackground(new java.awt.Color(0, 0, 0));
        jrbDeleteEmp.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jrbDeleteEmp.setForeground(new java.awt.Color(255, 0, 0));
        jrbDeleteEmp.setText("delete  employee");
        jrbDeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDeleteEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbDeleteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jrbAddEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jrbUpdateEmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jrbSearchEmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jrbShowAllEmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                                .addComponent(jrbQuit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 214, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbAddEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbSearchEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbShowAllEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jrbUpdateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbDeleteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnDoTask)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAddEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbAddEmpActionPerformed

    private void jrbQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbQuitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbQuitActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
        OptionsFrame opFrame=new OptionsFrame();
        opFrame.setTitle("EMPLOYEE MANAGEMENT APP.™");
        opFrame.setVisible(true); 
        opFrame.dispose();

        if(jrbAddEmp.isSelected())
        {
            AddEmployeeFrame addEmpFrame=new AddEmployeeFrame();
            addEmpFrame.setVisible(true);
            this.dispose();
        }
        else if(jrbSearchEmp.isSelected())
        {
            SearchEmployeeFrame searchEmpFrame=new SearchEmployeeFrame();
            searchEmpFrame.setVisible(true);
            this.dispose();
        }
        else if(jrbShowAllEmp.isSelected())
        {
            ViewAllEmployeeFrame viewAllEmpFrame=new ViewAllEmployeeFrame();
            viewAllEmpFrame.setVisible(true);
            this.dispose();
        }
        else if(jrbUpdateEmp.isSelected())
        {
            UpdateEmployeeFrame UpdateEmpFrame=new UpdateEmployeeFrame();
            UpdateEmpFrame.setVisible(true);
            this.dispose();
        }       
        else if(jrbDeleteEmp.isSelected())
        {
            DeleteEmployeeFrame deleteEmpFrame=new DeleteEmployeeFrame();
            deleteEmpFrame.setVisible(true);
            this.dispose();
        }
         else if(jrbQuit.isSelected())
        {
            int answer=JOptionPane.showConfirmDialog(null,"Are u sure ?","Quitting...",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            
                    if(answer==JOptionPane.YES_OPTION)
                    {
                        JOptionPane.showMessageDialog(null,"Thank you for using the app.™");
                        System.exit(0);
                    }
        }
         else
                    {
                        JOptionPane.showMessageDialog(null,"please make a selection first","Warning !",JOptionPane.WARNING_MESSAGE);
                    }
                       
                            
                                
        
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void jrbSearchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSearchEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSearchEmpActionPerformed

    private void jrbUpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbUpdateEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbUpdateEmpActionPerformed

    private void jrbDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDeleteEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbDeleteEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbAddEmp;
    private javax.swing.JRadioButton jrbDeleteEmp;
    private javax.swing.JRadioButton jrbQuit;
    private javax.swing.JRadioButton jrbSearchEmp;
    private javax.swing.JRadioButton jrbShowAllEmp;
    private javax.swing.JRadioButton jrbUpdateEmp;
    // End of variables declaration//GEN-END:variables
}
